config/routes.rb
Rails.application.routes.draw do
  get 'mypage', to: 'mypages#index'
  # resources :mypages
  devise_for :users
  # resources :users
  root to: 'articles#index'
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence:true
  validates :content, presence:true
  belongs_to :user

  has_many :tags_articles, dependent: :destroy  #親であるarticleが削除されたとき、それと紐づくtags_articlesも削除できるように追加
  has_many :tags, through: :tags_articles
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence:true

  has_many :tags_articles, dependent: :destroy #親であるarticleが削除されたとき、それと紐づくtags_articlesも削除できるように追加
  has_many :articles, through: :tags_articles
end

app/models/tags_article.rb
class TagsArticle < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :article, only: %i[ edit update destroy ]
  before_action :authenticate_user!, only: %i[ new edit create update destroy ]

  # GET /articles or /articles.json
  def index
    # @articles = Article.all.page(params[:page])
    # @articles = Article.where("title LIKE ?", "%#{params[:title]}%")

    if params[:title]
      @articles = Article.preload(:tags).where("title LIKE ?", "%#{params[:title]}%").page(params[:page])
    else
      @articles = Article.preload(:tags).all.page(params[:page])
    end
  end

  # GET /articles/1 or /articles/1.json
  def show
    @article = Article.find(params[:id])

  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

# binding.pry
    respond_to do |format|
      if @article.save
        # binding.pry
        format.html { redirect_to article_url(@article), notice: " 新たな記事を作成しました " }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: " 記事を更新しました " }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: " 記事を削除しました " }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def article
      @article = current_user.articles.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      binding.pry
      params.require(:article).permit(:title, :content, tag_ids: []).merge(user_id: current_user.id)
    end
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController

  def index
    # binding.pry
    @articles = current_user.articles.all.page(params[:page])

    if params[:title]
      @articles = current_user.articles.preload(:tags).where("title LIKE ?", "%#{params[:title]}%").page(params[:page])
    else
      @articles = current_user.articles.preload(:tags).all.page(params[:page])
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "つの問題") %> があります。</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.collection_check_boxes :tag_ids, Tag.all, :id, :name %>
  </div>

  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :content, class: "form-label" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit '保存', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/articles/_search.html.erb
<%= form_with url: articles_url, method: :get, local: true do |form| %>
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="mb-3">
        <%= form.label 'タイトル', class: "form-label" %>
        <%= form.text_field :title, value: params[:title], class: "form-control" %>
      </div>
      <div class="actions">
        <%= form.submit '検索', class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>記事編集</h1>

<%= render 'form', article: @article %>

<%= link_to '詳細', @article %> |
<%= link_to '戻る', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>記事</h1>
<%= render partial: "search" %>
<%= paginate @articles %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">タイトル</th>
      <th scope="col">本文</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td>
          <%= article.title %>
          <% article.tags.each do |tag| %>
            <span class="badge rounded-pill bg-primary"><%= tag.name %></span>
          <% end %>
        </td>
        <td><%= article.content %></td>
        <td>
          <%= link_to '詳細', article, class: "btn btn-success" %>
        </td>
      </tr>
    <% end %>

  </tbody>
</table>

app/views/articles/new.html.erb
<h1>新規記事</h1>

<%= render 'form', article: @article %>

<%= link_to '戻る', articles_path %>

app/views/articles/show.html.erb
<h1>記事詳細</h1>

<p id="notice"><%= notice %></p>

<div class="card">
  <div class="card-header">
    <%= @article.title %>
      <% @article.tags.each do |tag| %>
        <span class="badge rounded-pill bg-primary"><%= tag.name %></span>
      <% end %>
  </div>
  <div class="card-body">
    <%= @article.content %>
  </div>
</div>

<% if user_signed_in? && current_user.id == @article.user.id %>
  <%= link_to '編集', edit_article_path(@article), class: "btn btn-warning" %>

<% end %>
  <%= link_to '一覧', articles_path, class: "btn btn-secondary" %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'TOP', root_path, class: "btn btn-secondary" %>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
      <% if current_user %>
          <li class="nav-item">
            <%= link_to 'マイページ', mypage_path, class: "btn btn-secondary" %>
          </li>
          <li class="nav-item">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-secondary" %>
          </li>
      <% else %>
          <li class="nav-item">
            <%= link_to 'サインアップ', new_user_registration_path, class: "btn btn-secondary" %>
          </li>
          <li class="nav-item">
            <%= link_to 'ログイン', new_user_session_path, class: "btn btn-secondary" %>
          </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WonderfulPostApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render partial: "layouts/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/mypages/_search.html.erb
<%= form_with url: mypage_url, method: :get, local: true do |form| %>
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="mb-3">
        <%= form.label 'タイトル', class: "form-label" %>
        <%= form.text_field :title, value: params[:title], class: "form-control" %>
      </div>
      <div class="actions">
        <%= form.submit '検索', class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/mypages/index.html.erb
<h1>マイページ</h1>
<%= render partial: "search" %>
<%= link_to '記事作成', new_article_path, class: "btn btn-info" %>
  <table class="table">
  <table class="table">
  <thead>
    <tr>
      <th scope="col">タイトル</th>
      <th scope="col">本文</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
          <td>
            <%= article.title %>
            <% article.tags.each do |tag| %>
              <span class="badge rounded-pill bg-primary"><%= tag.name %></span>
            <% end %>
          </td>
        <td><%= article.content %></td>
        <td><%= link_to '詳細', article, class: "btn btn-success" %></td>
        <td><%= link_to '編集', edit_article_path(article), class: "btn btn-success" %></td>
        <td><%= link_to '削除', article, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-success" %></td>
      </tr>
    <% end %>
    <%= paginate @articles %>
  </tbody>